<a href="https://colab.research.google.com/github/Addakularanjith123/CodeNiharDEMLDS/blob/main/4_numpy_slicing_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align="center" style="color:blue">Codebasics Course: Numpy Slicing, Stacking </h2>

In [ ]:
import numpy as np

### Indexing, Slicing

In [ ]:
a = np.array([6,7,8,9])
a[0:2]

array([6, 7])

In [ ]:
a[2:]

array([8, 9])

In [ ]:
a[-1]

9

In [ ]:
a[-2:]

array([8, 9])

In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
b[1,2]

6

In [ ]:
b[2,0]

7

In [ ]:
b[0:2,2]

array([3, 6])

In [ ]:
b[-1]

array([7, 8, 9])

In [ ]:
b[-1, 0:2]

array([7, 8])

In [ ]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

### vstack, hstack

In [ ]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [ ]:
np.hstack((c, d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [ ]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U11')

In [ ]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

In [ ]:
f = np.vstack((c,e))
f

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U11')

### vsplit, hsplit

In [ ]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3])

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [ ]:
np.vsplit(transactions, [4])

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01'],
        ['104', 'David', '400.2', '2023-08-03']], dtype='<U32'),
 array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

### Boolean operations

In [ ]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [ ]:
monthly_sales[result]

array([30, 28])

In [ ]:
monthly_sales[result] = -1
monthly_sales

array([-1, 33, 35, -1, 42])

### Argmax

In [ ]:
index = np.argmax(monthly_sales)
index

4

In [ ]:
monthly_sales[4]

42

#### Now print a transaction with a maximum amount

In [ ]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [ ]:
transactions[:,2]

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [ ]:
transactions[:,2].astype(float)

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [ ]:
t_index = np.argmax(transactions[:,2].astype(float))
t_index

3

In [ ]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [ ]:
transactions[transactions[:,0]=="101"]

array([['101', 'Mohan', '250.5', '2023-08-01']], dtype='<U32')