<a href="https://colab.research.google.com/github/Addakularanjith123/CodeNiharDEMLDS/blob/main/Copy_of_Copy_of_Numpy_Slicing%2C_Stacking_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Indexing, Slicing

In [2]:
a = np.array([6,7,8,9])
a[0:2] #all the element from 0(inclusive) to 2(exclusive)

array([6, 7])

In [3]:
a[-4:-2] #from the -4 indexes to -2 index it's like a backword index

array([6, 7])

In [4]:
a[-4:2] #same but forward index (Here we have specified the index)

array([6, 7])

In [5]:
a[-3:] #from -3 index till end because there is no end index

array([7, 8, 9])

In [6]:
#If we want to print last 2 elements
a[2:] #colon and then nothing it means all the remaining elements

array([8, 9])

In [7]:
#If we want to print last 2 elements another way
a[-2:]

array([8, 9])

In [8]:
a[-2:3] #-2 is the starting index i.e 8 and upto index 3(exclusive) i.e(6,7,8,9) therefore it will satisfy only the -2 index element i.e 8

array([8])

In [9]:
a[-2:4] #this condition satisfy the last 2 elements

array([8, 9])

In [10]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#To print the 6
b[1,2]

np.int64(6)

In [13]:
print(b[1,2])

6


In [14]:
#To print the last row of the 2d array i.e b

b[-1]

array([7, 8, 9])

In [15]:
#Need only 1st two elements in the last row
b[-1, 0:2]

array([7, 8])

In [16]:
b[-1, :2]

array([7, 8])

### Column Level Slicing

In [17]:
b[:] #colon means all the rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Only 2nd(1st index) and 3rd(2nd index) column from all the rows

In [18]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [19]:
# e=c+d #the first array is 3 by 2 matrix and the second array is 3 by 3 matrix
#e

#If some information has in one array and remaining information in another array


In [20]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

#vstack,hstack

##Creating a combine array

In [21]:
# If we need some information in one array and the remaining information from another array
np.hstack((c,d)) #Horizontal stacking just putting 2 boxes together horizontally,we have to specify as tuple.

# Here the 1st col(101,102,103) has been repeated it is not doing join(merge will discuss in pandas)

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [22]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

## If few new customer are added later

In [23]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

In [24]:
#Here I want to join vertically it's like top of the another box added or appended the rows
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

# vsplit,hsplit

dividing the rows are columns

In [25]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3]) #spliting from row 3 here the date column is putting in the separate array

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [26]:
a,b=np.hsplit(transactions, [3])

In [27]:
a

array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'David', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32')

In [28]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [29]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

x=np.hsplit(transactions, [1,3]) #It split the from the 1st index to 2nd index(i.e 2nd and 3rd columns)

In [30]:
x

[array([['101'],
        ['102'],
        ['103'],
        ['104'],
        ['105']], dtype='<U32'),
 array([['Mohan', '250.5'],
        ['Bob', '150.0'],
        ['Fatima', '300.75'],
        ['David', '400.2'],
        ['Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [31]:
# x,y=np.hsplit(transactions, [1,3]) #it's generating the 3 objects of arrays but in the tuple unpact we only have 2 object

In [32]:
x,y,z=np.hsplit(transactions, [1,3])

In [33]:
x

array([['101'],
       ['102'],
       ['103'],
       ['104'],
       ['105']], dtype='<U32')

In [34]:
y

array([['Mohan', '250.5'],
       ['Bob', '150.0'],
       ['Fatima', '300.75'],
       ['David', '400.2'],
       ['Aryan', '330.1']], dtype='<U32')

In [35]:
z

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [36]:
import numpy as np

transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

# Build new rows
result = np.array([
    [row[0], row[1][:1], row[1][1:], row[2], row[3]]
    for row in transactions #here we are spliting col 1 twice in the every row
])

print(result) #row[1][:1]   # 'M' row[1][1:]   # 'ohan'


[['101' 'M' 'ohan' '250.5' '2023-08-01']
 ['102' 'B' 'ob' '150.0' '2023-08-02']
 ['103' 'F' 'atima' '300.75' '2023-08-01']
 ['104' 'D' 'avid' '400.2' '2023-08-03']
 ['105' 'A' 'ryan' '330.1' '2023-08-04']]


In [37]:
for row in transactions: #there is no allign
    print(f"{row[0]} {row[1][:1]} {row[1][1:]} {row[2]} {row[3]}")

101 M ohan 250.5 2023-08-01
102 B ob 150.0 2023-08-02
103 F atima 300.75 2023-08-01
104 D avid 400.2 2023-08-03
105 A ryan 330.1 2023-08-04


In [38]:
for row in transactions:
  print(f"{row[0]:<5} {row[1][:1]:<3} {row[1][1:]:<8} {row[2]:<8} {row[3]}")

101   M   ohan     250.5    2023-08-01
102   B   ob       150.0    2023-08-02
103   F   atima    300.75   2023-08-01
104   D   avid     400.2    2023-08-03
105   A   ryan     330.1    2023-08-04


In [39]:
# for i in row:
#   print(i)

In [40]:
for row in transactions:
  print(row)

['101' 'Mohan' '250.5' '2023-08-01']
['102' 'Bob' '150.0' '2023-08-02']
['103' 'Fatima' '300.75' '2023-08-01']
['104' 'David' '400.2' '2023-08-03']
['105' 'Aryan' '330.1' '2023-08-04']


vsplit

In [41]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.vsplit(transactions, [3])

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01']], dtype='<U32'),
 array([['104', 'David', '400.2', '2023-08-03'],
        ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

In [42]:
x,y=np.vsplit(transactions, [3])

In [43]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01']], dtype='<U32')

In [44]:
y

array([['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [45]:
y[1][2:]

array(['330.1', '2023-08-04'], dtype='<U32')

In [46]:
#one more column is added into the c array i.e second column(1st index) to
c = np.array([
    [101, 111.0,'Mira'],
    [102, 222.0,'Abdul'],
    [103, 333.0 ,'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])
e=c+d
e

array([['101101', '111.0250.5', 'Mira2023-08-01'],
       ['102102', '222.0150.0', 'Abdul2023-08-02'],
       ['103103', '333.0300.75', 'Andrea2023-08-01']], dtype='<U64')

### Boolean operations

In [47]:
#To find in which month we went for the below the target
monthly_sales = np.array([30, 33, 35, 28, 42]) #consider('Jan','Feb',.....)

result = monthly_sales < 32 #if the condition satisfies then it gives true value else false values(i.e boolean values)
result

array([ True, False, False,  True, False])

In [48]:
print(monthly_sales[result]) #To know the result value

[30 28]


In [49]:
monthly_sales[result] = -1 #replacing when the condition true with -1 value
monthly_sales

array([-1, 33, 35, -1, 42])

In monthly if we want to find out the maximum sales

In [50]:
monthly_sales.max() #just knowing the value not the index(like which month has highest sales)

np.int64(42)

#Argmax

In [51]:
index=np.argmax(monthly_sales)

In [52]:
index #in the 4th index the maximum value is present

np.int64(4)

In [53]:
monthly_sales[index] #To get the maximum value

np.int64(42)

#### Now print a transaction with a maximum amount

In [54]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [55]:
#to find the maximum value we first required the max col(i.e 3rd column(2nd indes) of the all rows)
transactions[:,2] # from all the rows need extracting only the 2nd column the datatype is 'U32 or U64'(uni code) i.e string

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [56]:
transactions[:,2].astype(float) #converting string datatype to float datatype

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [57]:
t_index=np.argmax(transactions[:,2].astype(float)) #we can get the 3rd index
t_index

np.int64(3)

In [58]:
transactions[t_index] #getting the index record or row

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

Codition checking


In [59]:
#Get a record with transaction id with 101
transactions[:,0] #getting only transaction id column

array(['101', '102', '103', '104', '105'], dtype='<U32')

In [60]:
transactions[transactions[:,0]=="101"] #checking the codition

array([['101', 'Mohan', '250.5', '2023-08-01']], dtype='<U32')